version: '3.9'
services:
  # backend:
  #   image: coppabacs-backend
  #   build: backend/.
  #   ports:
  #     - "8081:8081"
  #   expose:
  #     - "8081"
  #   command: mvn spring-boot:run
  #   networks:
  #     - coppabacs-networks
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://backend-db:5432/coppabacs
  #     SPRING_DATASOURCE_USERNAME: postgres
  #     SPRING_DATASOURCE_PASSWORD: password
  #   depends_on:
  #     - backend-db
  #     - keycloak

  # backend-db:
  #   image: postgres:16.0
  #   restart: always
  #   environment:
  #     POSTGRES_DB: coppabacs
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     TZ: America/Sao_Paulo
  #   ports:
  #     - "5436:5432"
  #   expose:
  #     - "5432"
  #   networks:
  #     - coppabacs-networks
  #   volumes:
  #     - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
    driver: local
  keycloak-pg-data:
    driver: local

networks:
  coppabacs-networks:
    driver: bridge
